<% if (typescript) { -%>
# BUILD STAGE
FROM node:<%= node_version %>-alpine as build

WORKDIR /app

<%- include('templates/nodejs/modulesCacheLayer.ejs'); %>

# Buid with dev dependencies (typescript)
COPY . .
RUN npm run build
RUN rm -r node_modules

# FINAL STAGE
FROM node:<%= node_version %>-alpine
ENV NODE_ENV=production

COPY --from=build /app/dist/ /app/dist/
# Install only production node_modules
<%- include('templates/nodejs/modulesCacheLayer.ejs'); %>

CMD ['npm', 'start']
<% } else { -%>
FROM node:<%= node_version %>-alpine
WORKDIR /app
ENV NODE_ENV=production

<%- include('templates/nodejs/modulesCacheLayer.ejs'); %>

COPY . .

CMD ['npm', 'start']
FROM nodejs
<% } -%>
