name: Deploy to Heroku Docker

on:
  push:
    branches:
      - "master"
env:
  APP_NAME: docker-generator

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "273.0.0"
          # service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - run: gsutil ls gs://example-bucket105

      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - uses: devmasx/cached-docker-build-push@v0.2.1
        with:
          image_name: registry.heroku.com/$APP_NAME/web
          cache_stage_target: build
          push: true
          # build_params: --build-arg=NPM_TOKEN=${{secrets.NPM_TOKEN}}

      - name: release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a $APP_NAME web
